# Generated by Django 2.1.9 on 2019-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.CharField(db_column='CompanyID', max_length=20, primary_key=True, serialize=False)),
                ('companyname', models.CharField(db_column='CompanyName', max_length=100)),
                ('companyphone', models.CharField(db_column='CompanyPhone', max_length=50)),
                ('companyaddress', models.CharField(db_column='CompanyAddress', max_length=250)),
                ('companyelectronicinvoicecode', models.CharField(blank=True, db_column='CompanyElectronicInvoiceCode', max_length=300, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceid', models.BigIntegerField(db_column='InvoiceId', primary_key=True, serialize=False)),
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=50, null=True)),
                ('customerid', models.CharField(blank=True, db_column='CustomerId', max_length=10, null=True)),
                ('customerphone', models.CharField(blank=True, db_column='CustomerPhone', max_length=20, null=True)),
                ('customeraddress', models.CharField(blank=True, db_column='CustomerAddress', max_length=150, null=True)),
                ('customeremail', models.CharField(blank=True, db_column='CustomerEmail', max_length=75, null=True)),
                ('invoicedate', models.DateField(db_column='InvoiceDate')),
                ('inithour', models.CharField(db_column='InitHour', max_length=50)),
                ('endhour', models.CharField(db_column='EndHour', max_length=50)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=18, null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'managed': False,
                'db_table': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='Paymenttype',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentId', primary_key=True, serialize=False)),
                ('paymentname', models.CharField(db_column='PaymentName', max_length=25)),
            ],
            options={
                'managed': False,
                'db_table': 'PaymentType',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rateid', models.AutoField(db_column='RateId', primary_key=True, serialize=False)),
                ('ratename', models.CharField(blank=True, db_column='RateName', max_length=100, null=True)),
                ('rateprice', models.DecimalField(blank=True, db_column='RatePrice', decimal_places=1, max_digits=19, null=True)),
                ('ratetime', models.IntegerField(blank=True, db_column='RateTime', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Rate',
            },
        ),
    ]
